#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@natflow[-1]
	add ucitrack natflow
	set ucitrack.@natflow[-1].init=natflow
	commit ucitrack
EOF

chmod 0755 /etc/init.d/natflow >/dev/null 2>&1

rm -f /tmp/luci-*cache
exit 0