#!/bin/sh /etc/rc.common

USE_PROCD=1

START=99

natflow_onoff()
{
	config_get_bool enabled "$1" enabled 1
	config_get_bool hwnat "$1" hwnat 1
	config_get_bool fullconenat "$1" fullconenat 1
	
	[ ! -e "/lib/modules/$(uname -r)/nft_fullcone.ko" ] && fullconenat="0"
	
	uci set firewall.@defaults[0].flow_offloading=$((!enabled))
	uci set firewall.@defaults[0].flow_offloading_hw=$((!enabled))
	uci set firewall.@defaults[0].fullcone="${fullconenat}"
	uci commit firewall
	/etc/init.d/firewall reload
	
	echo disabled=$((!enabled)) >/dev/natflow_ctl
	echo hwnat=$hwnat >/dev/natflow_ctl
	/etc/init.d/natflow-boot reload
}

start_service()
{
	config_load "natflow"
	config_foreach natflow_onoff natflow
}

service_triggers()
{
	procd_add_reload_trigger "natflow"
}